#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

# echo ACTION=$ACTION, DEVPATH=$DEVPATH, SUBSYSTEM=$SUBSYSTEM, BUSNUM=$BUSNUM >/dev/console

case "$BUSNUM" in
    001|002)
        USB="USB1"
        ;;
    003|004)
        USB="USB3"
        ;;
    *)
        exit 0
        ;;
esac

case "$ACTION" in
	add)
		#check if usb is connected
		#local bus=$(BUSNUM//0/)
		#bus=`cat /sys/bus/usb/drivers/usb/usb$bus/power/runtime_status`
		#if ["$bus" == "suspended"]
		#then
			#echo "ADD: " $ACTION $BUSNUM >> /dev/console
			#exit 0
		#fi
		# update LEDs
        	uci delete ledctrl.$USB.ledon
        	uci set ledctrl.$USB.duration='5000'
        	uci set ledctrl.$USB.delayon='500'
        	uci set ledctrl.$USB.delayoff='500'
        	uci set ledctrl.$USB.enable='on'
        ledcli $USB
		;;
	remove)
		# update LEDs
        uci set ledctrl.$USB.ledon='0'
        ledcli $USB
		;;
esac	
		
