#!/bin/sh

if [ "$INTERFACE" = "lan" ]; then
    exit 0
fi

. /lib/functions.sh
. /lib/functions/network.sh
 
if [ "$ACTION" = "ifup" ]; then
    local wanif
    if [ "$INTERFACE" != "wan" -a "$INTERFACE" != "internet" ]; then
        /usr/sbin/systime_sync &
    elif network_find_wan wanif; then
        if [ "$INTERFACE" = "$wanif" ]; then
            /usr/sbin/systime_sync &
        fi
    fi
fi
