#!/bin/sh /etc/rc.common

START=99zz
STOP=90

ipv6_enable() {
    config_load network
    config_get ifname wan ifname

    config_load protocol
    config_get enable wanv6 enable
	config_get passthrough wanv6 proto
	
    case "$enable" in 
        on)
            ubus list | grep -q 'network.interface.lanv6' && ubus call network.interface.lanv6 disconnect                  
            # enable wan ipv6
            echo "0" > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6
            ubus list | grep -q 'network.interface.lanv6' && ubus call network.interface.lanv6 connect
			if [ "$passthrough" = "passthrough" ]; then
			echo 0 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
			echo 1 > /sys/devices/virtual/net/br-lan/bridge/multicast_snooping
			fi
            ;;
        off)
            # disable wan ipv6
            echo "1" > /proc/sys/net/ipv6/conf/$ifname/disable_ipv6
            ;;
        *) 
            ;;
    esac
}

boot() {
    ipv6_enable
}

start() {
    return 0
}

stop() {
    return 0
}
